package dataComponent;


/**
 * @author xiaolu
 * Element of String Component
 * */
public class StringElement {
/**offset of a string in DEX file*/
public long address;
/**length of a string in DEX file*/
public long stringLength;
/**index of a string in string component generated by RAPID*/
public int stringId;
/**ASCII form of a string's content*/
public String stringContent;

}
