package dataComponent;

/**
 * Element of Method Component
 * Note: Basic data type is formated as 
 * 'void', 'boolean', 'byte', 'short', 'char', 'int', 'long', 'float', 'double'
 * The string format for class is 'a.b$c' e.g android.animation.AnimatorSet$Builder where Builder is an inner class
 * */
public class MethodElement {
	/**offset of a method definition in DEX file*/
	public long address;	
	/**Index of a method in Method Component generated by RAPID*/
	public int methodId;
	/**The string of the class type of a method */
	public String className;
	/**The string of the name of a method
	 * */
	public String methodName;
	/**The string of the returnValue type of a method
	 * No return value is represented by string 'void'.
	 * */
	public String returnValueType;
	/**The string array for the type of each parameter
	 * The value of this parameter can be NULL, if the 'returnValueType' field is 0;
	 * Avoiding 'NonePointerException' checking 'returnValueType' before using.
	 * */
	public String[] parameterType;
	/**True, if the method have a code block defined in DEX file, default is false.
	 **/
	public boolean hasCodeBlock=false;
	/**The instance of the codeBlock, the value of which can be NULL.
	 * Avoiding 'NonePointerException' checking flag 'hasCodeBlock' before using. 
	 * */
	public CodeBlock codeBlock;

	public MethodElement(){
		
	}
	/**
	 * Usually used for constructing the method for use's searching purpose.
	 * */
	public MethodElement(String className,String methodName,String returnValue,String[] parameterType){
		this.className=className;
		this.methodName=methodName;
		this.returnValueType=returnValue;
		this.parameterType=parameterType;
		
	}	
	/**
	 * Returning true if the parameterType[] is not NULL.
	 * */
	public boolean hasParameter(){
		if (parameterType==null)
			return false;
		else{
			return true;
		}
	}
	/**
	 * print fields of address, className, methodName ,returnValue and parameterType[]
	 * */
	public void printFields(){
		if(this.returnValueType==null){
			this.returnValueType="";
		}
		if(this.returnValueType==null){
			this.className="";
		}
		if(this.returnValueType==null){
			this.methodName="";
		}
		System.out.print("	"+this.address+"	"+this.returnValueType+" "+this.className+"."+this.methodName+" ");
		System.out.print("(");
		if(this.hasParameter()){
			
			for(int j=0;j<this.parameterType.length;j++){
				System.out.print(this.parameterType[j]);
				if(j!=(this.parameterType.length-1)){
					System.out.print(", ");
				}
			}
		
		}
		System.out.println(")");

	}
	
}
